### ISSUE TITLE
Use html & sign

### ISSUE THREAD

**Issue by sangjunp4rk** [Im3lectRick/prj-rev-bwfs-dasmoto#1]
Use the html & sign instead of just &, which is `&amp;`

https://github.com/Im3lectRick/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L5

**Comment by rickgradle** [comment]
Do I just type &amp for this? Or do I need to use quotes? I saw this issue, but wasn't sure what the right way to correct was.
