### ISSUE TITLE
Keep lines short

### ISSUE THREAD

**Issue by sangjunp4rk** [Im3lectRick/prj-rev-bwfs-dasmoto#4]
Your lines are a bit long right now. Try splitting this into new lines so it's easier to read on one screen without scrolling. Convention is usually ~79 characters per line.

https://github.com/Im3lectRick/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L15

**Comment by rickgradle** [comment]
Would you recommend putting breaks in the code? Or just creating new paragraph elements to split up the text? Using too many break elements seems like bad coding.
